<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17903" started-at="2017-10-26T20:19:39Z" finished-at="2017-10-26T20:19:57Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17903" started-at="2017-10-26T20:19:39Z" finished-at="2017-10-26T20:19:57Z">
      <class name="basics.HelloWorldTest">
        <test-method status="PASS" signature="beforeTestsetUp()[pri:0, instance:basics.HelloWorldTest@58651fd0]" name="beforeTestsetUp" is-config="true" duration-ms="3266" started-at="2017-10-26T16:19:39Z" finished-at="2017-10-26T16:19:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestsetUp -->
        <test-method status="PASS" signature="loginTest()[pri:1, instance:basics.HelloWorldTest@58651fd0]" name="loginTest" duration-ms="7139" started-at="2017-10-26T16:19:42Z" description="Verify Login" finished-at="2017-10-26T16:19:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="createAccounts()[pri:2, instance:basics.HelloWorldTest@58651fd0]" name="createAccounts" duration-ms="7472" started-at="2017-10-26T16:19:49Z" description="Create Accounts in Salesforce" finished-at="2017-10-26T16:19:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error: The number of accounts created does not match expected [2] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error: The number of accounts created does not match expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at basics.HelloWorldTest.createAccounts(HelloWorldTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createAccounts -->
      </class> <!-- basics.HelloWorldTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
